/* eslint-disable @next/next/no-page-custom-font */

import "./globals.css";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/Footer";
import { Providers } from "@/components/provider";
export const metadata = {
  title: "Saiful",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <head>
        <title>Wallet Management</title>

        <link
          rel="stylesheet"
          type="text/css"
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,600&family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,500;1,700&display=swap"
        />
      </head>
      <body>
        <Providers>
          <Navbar />
          <ToastContainer />
          <main className="min-h-screen pt-20">
           {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
